main: com.game.engine.GameEngine
name: GameEngine
version: 1
author: Morten
description: Game engine to create fast and simple minigames.
commands:
  game:
    description: Change gamestate of a lobby/game.
  hub:
    description: Connect you back to hub.